name: Publish to development (snapshot) repo
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          wrapper-directory: java/gradle/wrapper
          gradle-executable: java/gradlew

      - name: Publish package
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: publishMavenPublicationToDevelopmentRepository
          build-root-directory: java
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
          COMMIT_HASH: ${{ steps.commit.outputs.hash }}
          COMMIT_HASH_SHORT: ${{ steps.commit.outputs.short }}
